/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// @ts-ignore
const sidebars = {
  docs: [
    'intro',
    'rules',
    'menu',
    {
      type: 'category',
      label: '🖼 玩家教程',
      items: [
        'tutorial/Transportation',
        'tutorial/EchoMarket',
        'tutorial/PrismMarket',
        'tutorial/Milestone',
        'tutorial/Residence',
        'tutorial/Relation',
        {
          type: 'category',
          label: '🍾 BreweryX 酿酒指南',
          items: [
            {
              type: 'autogenerated',
              dirName: 'tutorial/BreweryX',
            }
          ],
        }
      ],
    },
  ],

  plugin_docs: [
    {
      type: 'category',
      label: 'PrismMarket 插件指南',
      link: {
        type: 'doc',
        id: 'plugins/PrismMarket/wiki/README',
      },
      items: [
        {
          type: 'category',
          label: '🚀 入门',
          items: [
            {
              type: 'autogenerated',
              dirName: 'plugins/PrismMarket/wiki/getting-started',
            }
          ],
        },
        {
          type: 'category',
          label: '🧱 配置',
          items: [
            {
              type: 'autogenerated',
              dirName: 'plugins/PrismMarket/wiki/configuration',
            }
          ],
        },
        {
          type: 'category',
          label: '🛠️ 运维',
          items: [
            {
              type: 'autogenerated',
              dirName: 'plugins/PrismMarket/wiki/operations',
            }
          ],
        },
        {
          type: 'category',
          label: '🧩 集成',
          items: [
            {
              type: 'autogenerated',
              dirName: 'plugins/PrismMarket/wiki/integrations',
            }
          ],
        },
        {
          type: 'category',
          label: '🏗️ 架构',
          items: [
            {
              type: 'autogenerated',
              dirName: 'plugins/PrismMarket/wiki/architecture',
            }
          ],
        },
      ],
    },
    'plugins/STYLE_GUIDE',
  ],
   
};

module.exports = sidebars;
