/**
 * 方块/家具查询数据
 *
 * 新增方块：在此文件追加一条记录即可，无需修改组件或页面。
 * 注意保持中英文描述同步填写。
 */

export interface BlockEntry {
  /** kebab-case 唯一标识，用于去重和关联引用 */
  id: string
  /** 图标路径，相对于站点根目录，如 "/images/teastory/paddy_field.png" */
  icon: string
  nameZh: string
  nameEn: string
  categoryZh: CategoryZh
  categoryEn: CategoryEn
  /** 简短描述（1~2 行） */
  descriptionZh: string
  descriptionEn: string
  /** 获取方式说明 */
  obtainZh: string
  obtainEn: string
  /** 可选属性键值对，显示在详情弹窗的表格中 */
  properties?: Record<string, string>
  /** 关联方块 id 列表，用于交叉链接 */
  relatedIds?: string[]
}

export const CATEGORIES_ZH = [
  '功能性方块',
  '家具',
  '工具',
  '容器',
  '植物与作物',
  '装饰方块',
  '灯具',
  '其他',
] as const

export const CATEGORIES_EN = [
  'Functional Block',
  'Furniture',
  'Tool',
  'Container',
  'Plants & Crops',
  'Decoration',
  'Lighting',
  'Other',
] as const

export type CategoryZh = (typeof CATEGORIES_ZH)[number]
export type CategoryEn = (typeof CATEGORIES_EN)[number]

/**
 * 根据传入的分类数组返回对应的英文或中文分类值。
 * 用于在组件中根据语言设置决定使用哪个分类列表。
 */
export function isCategoryZh(value: string): value is CategoryZh {
  return (CATEGORIES_ZH as readonly string[]).includes(value)
}

export function isCategoryEn(value: string): value is CategoryEn {
  return (CATEGORIES_EN as readonly string[]).includes(value)
}

export const allBlocks: BlockEntry[] = [
  // ─── 功能性方块 ───
  {
    id: 'paddy-field',
    icon: '/images/teastory/paddy_field.png',
    nameZh: '水田',
    nameEn: 'Paddy Field',
    categoryZh: '功能性方块',
    categoryEn: 'Functional Block',
    descriptionZh: '用于移栽水稻秧苗的耕田方块，具备浅水外观与交互限制。',
    descriptionEn: 'A flooded field for transplanting rice seedlings, with shallow-water visuals and interaction limits.',
    obtainZh: '工作台合成（6 泥土 + 1 水桶 → 6 水田）',
    obtainEn: 'Crafted (6 Dirt + 1 Water Bucket → 6 Paddy Fields)',
    properties: {
      硬度: '2.0',
      爆炸抗性: '3.0',
      工具: '任何锹',
    },
    relatedIds: ['xian-rice-seeds', 'item-xian-rice-seedling'],
  },
  {
    id: 'clay-kettle',
    icon: '/images/teastory/clay_kettle.png',
    nameZh: '陶壶（湿胚）',
    nameEn: 'Clay Kettle (Wet)',
    categoryZh: '功能性方块',
    categoryEn: 'Functional Block',
    descriptionZh: '未烧制的陶土茶壶胚体，放入熔炉烧制后变为空陶壶。',
    descriptionEn: 'Unfired clay kettle body. Smelt it in a furnace to obtain an empty clay kettle.',
    obtainZh: '工作台合成（陶土+粘土 → 陶壶胚）',
    obtainEn: 'Crafted from clay',
    relatedIds: ['pot-clay'],
  },
  {
    id: 'pot-clay',
    icon: '/images/teastory/pot_clay.png',
    nameZh: '陶壶',
    nameEn: 'Clay Pot',
    categoryZh: '功能性方块',
    categoryEn: 'Functional Block',
    descriptionZh: '可用于装水、烧水，是制作茶饮的基础容器之一。',
    descriptionEn: 'Can hold and boil water. A basic container for tea brewing.',
    obtainZh: '烧制陶壶胚获得',
    obtainEn: 'Smelted from clay kettle (wet)',
    properties: {
      容量: '1 桶水',
    },
  },
  {
    id: 'pot-porcelain',
    icon: '/images/teastory/pot_porcelain.png',
    nameZh: '瓷壶',
    nameEn: 'Porcelain Pot',
    categoryZh: '功能性方块',
    categoryEn: 'Functional Block',
    descriptionZh: '瓷质茶壶，保温性能适中，适合冲泡各类茶叶。',
    descriptionEn: 'Porcelain tea pot with moderate heat retention, suitable for all tea types.',
    obtainZh: '工作台合成',
    obtainEn: 'Crafted',
    relatedIds: ['pot-clay'],
  },
  {
    id: 'pot-zisha',
    icon: '/images/teastory/pot_zisha.png',
    nameZh: '紫砂壶',
    nameEn: 'Zisha Pot',
    categoryZh: '功能性方块',
    categoryEn: 'Functional Block',
    descriptionZh: '紫砂材质茶壶，保温性能优异，冲泡的茶饮品质更佳。',
    descriptionEn: 'Zisha clay tea pot with excellent heat retention, producing higher quality tea.',
    obtainZh: '使用 <span class="item-chip"><img src="/images/teastory/zisha_clay.png" alt="紫砂泥" />紫砂泥</span> 在工作台合成',
    obtainEn: 'Crafted from zisha clay',
    properties: {
      保温加成: '+15%',
    },
    relatedIds: ['zisha-clay', 'zisha-clay-cup'],
  },
  {
    id: 'pot-stone',
    icon: '/images/teastory/pot_stone.png',
    nameZh: '石壶',
    nameEn: 'Stone Pot',
    categoryZh: '功能性方块',
    categoryEn: 'Functional Block',
    descriptionZh: '石质茶壶，坚固耐用，保温一般。',
    descriptionEn: 'Stone tea pot, durable with average heat retention.',
    obtainZh: '工作台合成',
    obtainEn: 'Crafted',
  },
  {
    id: 'pot-iron',
    icon: '/images/teastory/pot_iron.png',
    nameZh: '铁壶',
    nameEn: 'Iron Pot',
    categoryZh: '功能性方块',
    categoryEn: 'Functional Block',
    descriptionZh: '铁质水壶，主要用于烧水，导热快。',
    descriptionEn: 'Iron kettle mainly used for boiling water with fast heat conduction.',
    obtainZh: '工作台合成（铁锭）',
    obtainEn: 'Crafted from iron ingots',
    properties: {
      烧水速度: '快',
    },
  },
  {
    id: 'water-pot-stone',
    icon: '/images/teastory/water_pot_stone.png',
    nameZh: '石水壶',
    nameEn: 'Stone Water Pot',
    categoryZh: '功能性方块',
    categoryEn: 'Functional Block',
    descriptionZh: '装有水的石壶，可在熔炉中烧开得到开水。',
    descriptionEn: 'Stone pot filled with water. Can be heated in a furnace to boil water.',
    obtainZh: '石壶 + 水桶',
    obtainEn: 'Stone pot + water bucket',
  },
  {
    id: 'water-pot-iron',
    icon: '/images/teastory/water_pot_iron.png',
    nameZh: '铁水壶',
    nameEn: 'Iron Water Pot',
    categoryZh: '功能性方块',
    categoryEn: 'Functional Block',
    descriptionZh: '装有水的铁壶，导热快，烧水效率高。',
    descriptionEn: 'Iron pot filled with water. Fast heat conduction for efficient boiling.',
    obtainZh: '铁壶 + 水桶',
    obtainEn: 'Iron pot + water bucket',
  },
  {
    id: 'water-pot-porcelain',
    icon: '/images/teastory/water_pot_porcelain.png',
    nameZh: '瓷水壶',
    nameEn: 'Porcelain Water Pot',
    categoryZh: '功能性方块',
    categoryEn: 'Functional Block',
    descriptionZh: '装有水的瓷壶，保温适中。',
    descriptionEn: 'Porcelain pot filled with water. Moderate heat retention.',
    obtainZh: '瓷壶 + 水桶',
    obtainEn: 'Porcelain pot + water bucket',
  },
  {
    id: 'water-pot-zisha',
    icon: '/images/teastory/water_pot_zisha.png',
    nameZh: '紫砂水壶',
    nameEn: 'Zisha Water Pot',
    categoryZh: '功能性方块',
    categoryEn: 'Functional Block',
    descriptionZh: '装有水的紫砂壶，保温性能优异。',
    descriptionEn: 'Zisha pot filled with water. Excellent heat retention.',
    obtainZh: '紫砂壶 + 水桶',
    obtainEn: 'Zisha pot + water bucket',
  },

  // ─── 家具 ───
  {
    id: 'zisha-clay',
    icon: '/images/teastory/zisha_clay.png',
    nameZh: '紫砂泥',
    nameEn: 'Zisha Clay',
    categoryZh: '装饰方块',
    categoryEn: 'Decoration',
    descriptionZh: '稀有的紫色粘土，可用于制作紫砂壶和紫砂杯。',
    descriptionEn: 'Rare purple clay used for crafting zisha pots and cups.',
    obtainZh: '世界战利品箱掉落、与村民交易',
    obtainEn: 'World loot chests, villager trading',
    relatedIds: ['pot-zisha', 'zisha-clay-cup'],
  },
  {
    id: 'zisha-clay-cup',
    icon: '/images/teastory/zisha_clay_cup.png',
    nameZh: '紫砂泥杯（湿胚）',
    nameEn: 'Zisha Cup (Wet)',
    categoryZh: '家具',
    categoryEn: 'Furniture',
    descriptionZh: '未烧制的紫砂杯胚体，烧制后变为紫砂杯。',
    descriptionEn: 'Unfired zisha cup body. Fires into a zisha cup.',
    obtainZh: '工作台合成（紫砂泥）',
    obtainEn: 'Crafted from zisha clay',
    relatedIds: ['zisha-clay', 'cup-zisha'],
  },
  {
    id: 'cup-zisha',
    icon: '/images/teastory/cup_zisha.png',
    nameZh: '紫砂杯',
    nameEn: 'Zisha Cup',
    categoryZh: '家具',
    categoryEn: 'Furniture',
    descriptionZh: '紫砂材质的茶杯，可与茶壶配合盛装茶饮。',
    descriptionEn: 'Zisha tea cup for serving tea from a pot.',
    obtainZh: '烧制紫砂泥杯获得',
    obtainEn: 'Fired from zisha cup (wet)',
    properties: {
      容量: '1 份茶饮',
    },
    relatedIds: ['zisha-clay', 'zisha-clay-cup'],
  },
  {
    id: 'cup-porcelain',
    icon: '/images/teastory/cup_porcelain.png',
    nameZh: '瓷杯',
    nameEn: 'Porcelain Cup',
    categoryZh: '家具',
    categoryEn: 'Furniture',
    descriptionZh: '瓷质茶杯，经典雅致，适合盛装各类茶饮。',
    descriptionEn: 'Porcelain tea cup, classic and elegant for serving tea.',
    obtainZh: '工作台合成',
    obtainEn: 'Crafted',
    relatedIds: ['pot-porcelain'],
  },
  {
    id: 'cup-glass',
    icon: '/images/teastory/cup_glass.png',
    nameZh: '玻璃杯',
    nameEn: 'Glass Cup',
    categoryZh: '家具',
    categoryEn: 'Furniture',
    descriptionZh: '透明玻璃杯，适合盛装颜色清亮的茶饮。',
    descriptionEn: 'Transparent glass cup, ideal for serving bright-colored teas.',
    obtainZh: '工作台合成（玻璃）',
    obtainEn: 'Crafted from glass',
  },
  {
    id: 'cup-stone',
    icon: '/images/teastory/cup_stone.png',
    nameZh: '石杯',
    nameEn: 'Stone Cup',
    categoryZh: '家具',
    categoryEn: 'Furniture',
    descriptionZh: '石质杯子，古朴厚重。',
    descriptionEn: 'Stone cup, rustic and sturdy.',
    obtainZh: '工作台合成',
    obtainEn: 'Crafted',
  },
  {
    id: 'cup-wood',
    icon: '/images/teastory/cup_wood.png',
    nameZh: '木杯',
    nameEn: 'Wood Cup',
    categoryZh: '家具',
    categoryEn: 'Furniture',
    descriptionZh: '木质杯子，质朴自然。',
    descriptionEn: 'Wooden cup, natural and simple.',
    obtainZh: '工作台合成（木材）',
    obtainEn: 'Crafted from wood planks',
  },
  {
    id: 'clay-cup',
    icon: '/images/teastory/clay_cup.png',
    nameZh: '陶杯（湿胚）',
    nameEn: 'Clay Cup (Wet)',
    categoryZh: '家具',
    categoryEn: 'Furniture',
    descriptionZh: '未烧制的陶土杯胚体，烧制后变为陶杯。',
    descriptionEn: 'Unfired clay cup body. Fires into a clay cup.',
    obtainZh: '工作台合成（粘土）',
    obtainEn: 'Crafted from clay',
  },

  // ─── 工具 ───
  {
    id: 'wooden-mortar-pestle',
    icon: '/images/teastory/wooden_mortar_and_pestle.png',
    nameZh: '木制研钵研杵',
    nameEn: 'Wooden Mortar & Pestle',
    categoryZh: '工具',
    categoryEn: 'Tool',
    descriptionZh: '用于将青叶研磨成碎茶叶的基础工具，每次使用消耗 1 耐久。',
    descriptionEn: 'Basic tool for grinding tea leaves into broken tea. Consumes 1 durability per use.',
    obtainZh: '工作台合成',
    obtainEn: 'Crafted',
    properties: {
      耐久: '80',
      用途: '青叶 → 碎茶（1 青叶 → 3 碎茶）',
    },
    relatedIds: ['tea-whisk', 'tea-leaf'],
  },
  {
    id: 'tea-whisk',
    icon: '/images/teastory/tea_whisk.png',
    nameZh: '茶筅',
    nameEn: 'Tea Whisk',
    categoryZh: '工具',
    categoryEn: 'Tool',
    descriptionZh: '用于制作抹茶的工具，每次研磨消耗 1 耐久。',
    descriptionEn: 'Tool for preparing matcha. Consumes 1 durability per use.',
    obtainZh: '工作台合成',
    obtainEn: 'Crafted',
    properties: {
      耐久: '120',
      用途: '制作抹茶粉',
    },
    relatedIds: ['wooden-mortar-pestle'],
  },
  {
    id: 'sickle',
    icon: '/images/teastory/sickle.png',
    nameZh: '镰刀',
    nameEn: 'Sickle',
    categoryZh: '工具',
    categoryEn: 'Tool',
    descriptionZh: '用于收割水稻等作物，提高采收效率。',
    descriptionEn: 'Used for harvesting rice and other crops with improved efficiency.',
    obtainZh: '工作台合成',
    obtainEn: 'Crafted',
    properties: {
      工具类型: '剑/锄混合',
    },
    relatedIds: ['paddy-field'],
  },

  // ─── 植物与作物 ───
  {
    id: 'tea-seeds',
    icon: '/images/teastory/tea_seeds.png',
    nameZh: '茶树种子',
    nameEn: 'Tea Seeds',
    categoryZh: '植物与作物',
    categoryEn: 'Plants & Crops',
    descriptionZh: '一切的起源。可在耕地上种植茶树，生长后采集鲜叶。',
    descriptionEn: 'The origin of everything. Plant on farmland to grow tea bushes for leaf harvesting.',
    obtainZh: '世界战利品箱掉落',
    obtainEn: 'World loot chests',
    properties: {
      种植: '耕地',
      成熟时长: '受季节与节气影响',
    },
    relatedIds: ['fresh-tea-leaf'],
  },
  {
    id: 'xian-rice-seeds',
    icon: '/images/teastory/xian_rice_seeds.png',
    nameZh: '稻谷',
    nameEn: 'Rice Seeds',
    categoryZh: '植物与作物',
    categoryEn: 'Plants & Crops',
    descriptionZh: '水稻种子，可在耕地上育秧，成熟后收获水稻秧苗。',
    descriptionEn: 'Rice seeds for seedling cultivation. Plant on farmland to obtain rice seedlings.',
    obtainZh: '成熟水稻掉落（1~3 个）',
    obtainEn: 'Dropped by mature rice plants (1-3)',
    relatedIds: ['item-xian-rice-seedling', 'paddy-field', 'xian-rice'],
  },
  {
    id: 'item-xian-rice-seedling',
    icon: '/images/teastory/item_xian_rice_seedling.png',
    nameZh: '水稻秧苗',
    nameEn: 'Rice Seedling',
    categoryZh: '植物与作物',
    categoryEn: 'Plants & Crops',
    descriptionZh: '在普通耕地育秧获得的秧苗，需要移栽至水田继续生长。',
    descriptionEn: 'Seedling grown on farmland. Must be transplanted to a paddy field for continued growth.',
    obtainZh: '在耕地种植稻谷成熟后收获',
    obtainEn: 'Harvested from mature rice plants on farmland',
    relatedIds: ['xian-rice-seeds', 'paddy-field'],
  },
  {
    id: 'xian-rice',
    icon: '/images/teastory/xian_rice.png',
    nameZh: '大米',
    nameEn: 'Rice',
    categoryZh: '植物与作物',
    categoryEn: 'Plants & Crops',
    descriptionZh: '使用木制研钵研杵加工稻谷获得的大米，可用于烹饪。',
    descriptionEn: 'Rice obtained by processing rice seeds with a mortar and pestle. Used in cooking.',
    obtainZh: '木制研钵研杵 + 稻谷 → 大米',
    obtainEn: 'Mortar & pestle + rice seeds → rice',
    relatedIds: ['xian-rice-seeds', 'wooden-mortar-pestle'],
  },

  // ─── 容器 ───
  {
    id: 'empty-tea-bag',
    icon: '/images/teastory/empty_tea_bag.png',
    nameZh: '空茶包',
    nameEn: 'Empty Tea Bag',
    categoryZh: '容器',
    categoryEn: 'Container',
    descriptionZh: '用于盛装茶叶的空包，可装入 6 份对应茶叶制成茶包。',
    descriptionEn: 'Empty bag for holding tea leaves. Holds 6 portions of tea leaves.',
    obtainZh: '工作台合成（1 线 + 5 纸 → 3 空茶包）',
    obtainEn: 'Crafted (1 String + 5 Paper → 3 Empty Tea Bags)',
    properties: {
      容量: '6 茶叶 → 1 茶包',
    },
  },
  {
    id: 'baking-powder',
    icon: '/images/teastory/baking_powder.png',
    nameZh: '发酵粉',
    nameEn: 'Baking Powder / Fermentation Powder',
    categoryZh: '功能性方块',
    categoryEn: 'Functional Block',
    descriptionZh: '用于茶叶发酵工序的必需品，每一步发酵都需要 1 份。可从茶渣回收获得。',
    descriptionEn: 'Essential for the tea fermentation process. Each step consumes 1 powder. Can be recycled from tea residue.',
    obtainZh: '任意 2 份茶渣 → 1 发酵粉',
    obtainEn: 'Recycled from 2 tea residues → 1 fermentation powder',
    properties: {
      回收配方: '2 茶渣 → 1 发酵粉',
      用途: '发酵工序消耗品',
    },
  },

  // ─── 茶饮成品 ───
  {
    id: 'black-tea-bag',
    icon: '/images/teastory/black_tea_bag.png',
    nameZh: '红茶包',
    nameEn: 'Black Tea Bag',
    categoryZh: '其他',
    categoryEn: 'Other',
    descriptionZh: '装有红茶叶的茶包，配合茶壶和开水可冲泡红茶。',
    descriptionEn: 'Tea bag filled with black tea leaves. Brew with a kettle and hot water.',
    obtainZh: '1 空茶包 + 6 红茶茶叶 → 1 红茶包',
    obtainEn: '1 Empty tea bag + 6 Black tea leaves → 1 Black tea bag',
    relatedIds: ['empty-tea-bag'],
  },
  {
    id: 'green-tea-bag',
    icon: '/images/teastory/green_tea_bag.png',
    nameZh: '绿茶包',
    nameEn: 'Green Tea Bag',
    categoryZh: '其他',
    categoryEn: 'Other',
    descriptionZh: '装有绿茶茶叶的茶包。',
    descriptionEn: 'Tea bag filled with green tea leaves.',
    obtainZh: '1 空茶包 + 6 绿茶茶叶 → 1 绿茶包',
    obtainEn: '1 Empty tea bag + 6 Green tea leaves → 1 Green tea bag',
    relatedIds: ['empty-tea-bag'],
  },
  {
    id: 'oolong-tea-bag',
    icon: '/images/teastory/oolong_tea_bag.png',
    nameZh: '乌龙茶包',
    nameEn: 'Oolong Tea Bag',
    categoryZh: '其他',
    categoryEn: 'Other',
    descriptionZh: '装有乌龙茶叶的茶包。',
    descriptionEn: 'Tea bag filled with oolong tea leaves.',
    obtainZh: '1 空茶包 + 6 乌龙茶叶 → 1 乌龙茶包',
    obtainEn: '1 Empty tea bag + 6 Oolong tea leaves → 1 Oolong tea bag',
    relatedIds: ['empty-tea-bag'],
  },
  {
    id: 'white-tea-bag',
    icon: '/images/teastory/white_tea_bag.png',
    nameZh: '白茶包',
    nameEn: 'White Tea Bag',
    categoryZh: '其他',
    categoryEn: 'Other',
    descriptionZh: '装有白茶叶的茶包。',
    descriptionEn: 'Tea bag filled with white tea leaves.',
    obtainZh: '1 空茶包 + 6 白茶叶 → 1 白茶包',
    obtainEn: '1 Empty tea bag + 6 White tea leaves → 1 White tea bag',
    relatedIds: ['empty-tea-bag'],
  },
  {
    id: 'puer-tea-bag',
    icon: '/images/teastory/puer_tea_bag.png',
    nameZh: '普洱茶包',
    nameEn: "Pu'er Tea Bag",
    categoryZh: '其他',
    categoryEn: 'Other',
    descriptionZh: '装有普洱茶叶的茶包。',
    descriptionEn: "Tea bag filled with Pu'er tea leaves.",
    obtainZh: '1 空茶包 + 6 普洱茶叶 → 1 普洱茶包',
    obtainEn: "1 Empty tea bag + 6 Pu'er tea leaves → 1 Pu'er tea bag",
    relatedIds: ['empty-tea-bag'],
  },
  {
    id: 'yellow-tea-bag',
    icon: '/images/teastory/yellow_tea_bag.png',
    nameZh: '黄茶包',
    nameEn: 'Yellow Tea Bag',
    categoryZh: '其他',
    categoryEn: 'Other',
    descriptionZh: '装有黄茶叶的茶包。',
    descriptionEn: 'Tea bag filled with yellow tea leaves.',
    obtainZh: '1 空茶包 + 6 黄茶叶 → 1 黄茶包',
    obtainEn: '1 Empty tea bag + 6 Yellow tea leaves → 1 Yellow tea bag',
    relatedIds: ['empty-tea-bag'],
  },
]
